In [65]:
import numpy as np

In [66]:
Q=np.array([
    [5,1,2],
    [1,1,3],
    [0,2,5]
])
K=np.array([
    [1,2,3],
    [1,0,2],
    [1,0,1]
])
V=np.array([
    [4,5,6],
    [1,2,3],
    [5,4,5]
])

In [67]:
def attention(Q,K,V):
  d_K=K.shape[-1]
  sim=np.dot(Q,K.T)/np.sqrt(d_K)

  return sim

In [68]:
def softmax(x):
  x=x-np.max(x,axis=-1,keepdims=True)
  exp_x=np.exp(x)
  return exp_x/np.sum(exp_x,axis=-1,keepdims=True)

In [69]:
attention_score=attention(Q,K,V)
attention_weight=softmax(attention_score)
output=attention_weight @ V
print('Attention score:\n',attention_score)
print("Attention weight\n:",attention_weight)
print("Attention output\n:",output)

Attention score:
 [[ 7.5055535   5.19615242  4.04145188]
 [ 6.92820323  4.04145188  2.30940108]
 [10.96965511  5.77350269  2.88675135]]
Attention weight
: [[8.84469034e-01 8.78461006e-02 2.76848654e-02]
 [9.38419364e-01 5.23234992e-02 9.25713660e-03]
 [9.94187380e-01 5.50564141e-03 3.06978346e-04]]
Attention output
: [[3.76414656 4.70877683 5.70877683]
 [3.85228664 4.83377237 5.83377237]
 [3.98379005 4.9831761  5.9831761 ]]
